name: Build model-cli

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build model-cli
        run: |
          make release VERSION=${{ github.sha }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/
          retention-days: 2
          if-no-files-found: error
